# Generated by Django 4.2.3 on 2023-07-19 23:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0003_alter_listing_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.CharField(blank=True, max_length=10000),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.CharField(blank=True, max_length=1000),
        ),
    ]
