# Generated by Django 4.2.3 on 2023-07-20 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("auctions", "0004_alter_listing_description_alter_listing_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="auctions.category",
            ),
        ),
        migrations.AlterField(
            model_name="listing",
            name="description",
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name="listing",
            name="image",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
